project:
  type: website
  output-dir: docs

website:
  title: "Personal Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: personal_project.qmd
        text: Projects
      - href: hobbies.qmd
        text: Hobbies
      - href: show.qmd
        text: Show
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


